# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: publish

on:
  push:
    tags:
      - v*

jobs:

  publish:

    runs-on: ubuntu-latest

    env:
      PUBLISH_OPTS: ${{ github.ref_name == 'master' && '--verbose' || '--verbose --tag beta' }}
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      
      - name: Get Branch
       run: |
         raw=$(git branch -r --contains ${{ github.ref }})
         branch=${raw/origin\/}
         echo ::set-env name=BRANCH::$branch

      - name: print branch
        run: |
          echo ${{ env.BRANCH }}

      - name: get version from package.json
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./package.json
          property: version

      - name: before scripts
        run: |
          echo "Current publish version: ${{ env.VERSION }}"
        env:
          VERSION: ${{ steps.version.outputs.value }}

      - name: install packages
        run: |
          npm ci

      - name: publish
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm publish $PUBLISH_OPTS --access public
