name: test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true
        # default: 'zhaoyiming0803'
      email:
        description: 'Email'
        required: true
        # default: 'zhaoyiming0803@gmail.com'

jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      PUBLISH_OPTS: ${{ github.ref == 'refs/heads/master' && '--verbose13' || '--verbose --tag=alpha' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: before script
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/id_rsa
          touch ~/.ssh/config
          chmod 700 ~/.ssh/id_rsa
          echo "SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}"
          echo "CI_COMMIT_REF_NAME: ${{ github.ref }}"
    
      - name: install packages
        run: |
          npm ci
          npm run print
          echo "PUBLISH_OPTS: $PUBLISH_OPTS"

      - name: upload oss
        run: |
          npm run oss
          echo "Hello ${{ github.event.inputs.name }}!"

      - name: release package
        run: |
          npm run release
          echo "Email ${{ github.event.inputs.email }}!"
