name: test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true
        # default: 'zhaoyiming0803'
      email:
        description: 'Email'
        required: true
        # default: 'zhaoyiming0803@gmail.com'

jobs:

  print:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: |
          npm ci
          npm run print

  oss:
    runs-on: ubuntu-latest
    needs: [print]
    steps:
      - run: |
          npm run oss
          echo "Hello ${{ github.event.inputs.name }}!"

  release:
    runs-on: ubuntu-latest
    needs: [oss]
    steps:
      - run: |
          npm run release
          echo "Email is ${{ github.event.inputs.email }}!"
