name: test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true
        # default: 'zhaoyiming0803'
      email:
        description: 'Email'
        required: true
        # default: 'zhaoyiming0803@gmail.com'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: before script
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/id_rsa
          touch ~/.ssh/config
          chmod 700 ~/.ssh/id_rsa
          echo "SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "CI_COMMIT_REF_NAME: ${{ github.ref }}"
#         if: ${{ github.ref == 'refs/heads/master' }}
#           echo "This event is a pull request that had an assignee removed."
      
      - name: install packages
        run: |
          npm ci
          npm run print

      - name: upload oss
        run: |
          npm run oss
          echo "Hello ${{ github.event.inputs.name }}!"

      - name: release package
        run: |
          npm run release
          echo "Email ${{ github.event.inputs.email }}!"
