name: test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true
        # default: 'zhaoyiming0803'
      email:
        description: 'Email'
        required: true
        # default: 'zhaoyiming0803@gmail.com'

jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      PUBLISH_OPTS: ${{ github.ref == 'refs/heads/master' && '--verbose' || '--verbose --tag=alpha' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: before script
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/id_rsa
          touch ~/.ssh/config
          chmod 700 ~/.ssh/id_rsa
          echo "SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}"
          echo "CI_COMMIT_REF_NAME: ${{ github.ref }}"
          echo "GITHUB_REF_NAME: ${{ github.ref_name }}"
      
      - name: get version from package.json
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./package.json
          property: version
    
      - name: install packages
#         uses: actions/cache@v2
#         with:
#           path: build
#           key: ${{ github.ref_name }}
        run: |
          npm ci
          npm run print
          echo "PUBLISH_OPTS: $PUBLISH_OPTS"
      
      - name: setup oss
        uses: yizhoumo/setup-ossutil@v1
        with: 
          ossutil-version: '1.7.0' # Optional, default to '1.7.0'
          endpoint: ${{ secrets.OSS_REGION_PROD }}
          access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY }}
          access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}

      - name: upload oss
        run: |
          echo "Hello ${{ github.event.inputs.name }}，上传打包到 CDN"
          echo "VERSION: ${{ steps.version.outputs.value }}"
          ossutil cp -f -r build oss://$CDN_OSS_PROD/test/$VERESION/
        env:
          VERESION: ${{ steps.version.outputs.value }}

      - name: release package
        run: |
          npm run release
          echo "Email ${{ github.event.inputs.email }}!"
