name: test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true
        default: 'zhaoyiming0803'
      email:
        description: 'Email'
        required: true
        default: 'zhaoyiming0803@gmail.com'

jobs:
  installPackages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: |
        npm ci
        echo "Hello ${{ github.event.inputs.name }}!"
        echo "- Email is ${{ github.event.inputs.email }}!"
  runPrintFunction:
    runs-on: ubuntu-latest
    steps:
      - run: |
        npm run print